import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styleCreateAd = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFF',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        height: 60,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#1A1A1A',
    },
    scrollContent: {
        padding: 20,
        paddingBottom: 40,
    },
    photoUploadArea: {
        width: '100%',
        height: 200,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: '#E0E0E0',
        borderStyle: 'dashed',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FCFCFC',
        marginBottom: 30,
    },
    photoSection: {
        marginBottom: 30,
    },
    photoIconContainer: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: '#FFF',
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        marginBottom: 10,
    },
    photoUploadTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#1A1A1A',
    },
    photoUploadSubtitle: {
        fontSize: 12,
        color: '#999',
        marginTop: 5,
    },
    labelHorizontal: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#999',
        marginBottom: 15,
        letterSpacing: 0.5,
    },
    imageHorizontalScroll: {
        flexDirection: 'row',
    },
    miniAddButton: {
        width: 100,
        height: 100,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: '#E0E0E0',
        borderStyle: 'dashed',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FCFCFC',
        marginRight: 15,
    },
    miniAddText: {
        fontSize: 10,
        fontWeight: 'bold',
        color: '#999',
        marginTop: 5,
    },
    miniImageContainer: {
        width: 100,
        height: 100,
        marginRight: 15,
        position: 'relative',
    },
    miniImage: {
        width: 100,
        height: 100,
        borderRadius: 20,
    },
    miniRemoveButton: {
        position: 'absolute',
        top: -5,
        right: -5,
        backgroundColor: '#1A1A1A',
        width: 24,
        height: 24,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#FFF',
    },
    inputGroup: {
        marginBottom: 25,
    },
    label: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#999',
        marginBottom: 10,
        letterSpacing: 0.5,
    },
    input: {
        fontSize: 16,
        color: '#1A1A1A',
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
        paddingVertical: 10,
    },
    toggleContainer: {
        flexDirection: 'row',
        backgroundColor: '#F8F9FA',
        borderRadius: 15,
        padding: 5,
    },
    toggleButton: {
        flex: 1,
        paddingVertical: 12,
        alignItems: 'center',
        borderRadius: 12,
    },
    toggleButtonActive: {
        backgroundColor: '#16B37B', // Cores mais vivas como no design
        elevation: 3,
        shadowColor: '#16B37B',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
    },
    toggleText: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#7F8C8D',
    },
    toggleTextActive: {
        color: '#FFF',
    },
    priceInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    currencyPrefix: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#1A1A1A',
        marginRight: 5,
    },
    priceInput: {
        flex: 1,
        fontSize: 18,
        fontWeight: 'bold',
        color: '#1A1A1A',
        paddingVertical: 10,
    },
    dropdownHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#F8F9FA',
        borderRadius: 15,
        padding: 15,
    },
    dropdownHeaderText: {
        fontSize: 16,
        color: '#1A1A1A',
    },
    dropdownList: {
        marginTop: 10,
        backgroundColor: '#FFF',
        borderRadius: 20,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 5 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        padding: 5,
    },
    dropdownItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 15,
        borderRadius: 15,
    },
    dropdownItemText: {
        fontSize: 16,
        color: '#4A4A4A',
    },
    dropdownItemTextActive: {
        color: '#2D6A4F',
        fontWeight: 'bold',
    },
    textArea: {
        backgroundColor: '#F8F9FA',
        borderRadius: 20,
        padding: 15,
        height: 120,
        textAlignVertical: 'top',
        borderBottomWidth: 0,
    },
    weightInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    weightInput: {
        flex: 1,
        fontSize: 16,
        color: '#1A1A1A',
        paddingVertical: 10,
    },
    weightSuffix: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#999',
    },
    publishButton: {
        backgroundColor: '#16B37B',
        borderRadius: 15,
        height: 55,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 10,
        elevation: 4,
        shadowColor: '#16B37B',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
    },
    publishButtonText: {
        color: '#FFF',
        fontSize: 18,
        fontWeight: 'bold',
    },
    boostToggleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F0F9F4',
        padding: 15,
        borderRadius: 15,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: '#C8E6C9',
    },
    boostCheckbox: {
        width: 24,
        height: 24,
        borderRadius: 6,
        borderWidth: 2,
        borderColor: '#16B37B',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    boostCheckboxActive: {
        backgroundColor: '#16B37B',
    },
    boostTextContainer: {
        flex: 1,
    },
    boostTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#1A1A1A',
    },
    boostSubtitle: {
        fontSize: 12,
        color: '#666',
        marginTop: 2,
    },
});
